apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017 # Porta do serviço
      targetPort: 27017 # Porta do container
  type: ClusterIP
